name: CI/CD

on:
  push:
    branches:
      - main
      - PradyumnaNaik

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: yarn install

      - name: Build Strapi
        run: yarn build

      - name: Deploy with PM2
        run: |
          pm2 stop strapi || true
          pm2 start yarn --name strapi -- start

